[connections.gcs]
type = "service_account"
project_id = "lewagon-batch672"
private_key_id = "64c06a2cdf194837299712562bac95b34540a2fb"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCn2QGJ7MYNE5hb
7EgegwWRzOyQAMUMBxe8eru7gKTfcrme0ZNiRP5rsjjIS7ocV+Lz1u0RM+bwW2PB
+Z+9Tga+rG4jv+1RFFlGXeXaMa/mZaO6VGin9cTLwTEdRu9Sj2YX6qp6TIB3KbNB
Vzq9j4SpR+hLxulCM3T1td3LJbOxK88xNf+Xse1KC3i4zlv3XzqgiRJGisN/vuDz
osljO1Yaj6VQbyDNtvYvYeb1mNomO+UgqCULPIX/G6z8QDzH/UMJ/wb2Xfarm63q
pYjxj7HDf7rpyWe7p+0pdykNTfYkyxa6dDQaMCq/FKvmc7Ocr5pcdlg1027ZTdb1
Ty+BxbIfAgMBAAECggEAMSXT04UnQPD57gCz5WtMGDM/GbN//1OcWa4+hlrW7C71
t1F6rI2zSem3wr6Z0m7Rn8DRTfY6qyq3fTcQ1SehxfdLkOBEJzekJHyeL1PZQ8eD
N647ruLCKz94mDALJ8uhg2NNY94+x6XIPVvDcXoyyDasCHRIHQBgQQpt1WxGv5uw
xvjPz9Fi7ZHtRx3JTNdnGFz4W4p57/KlZkLd6wriOwateOaw7k2+50JEV4ZpgwdF
Rm7E72CLVUmZoVWVmq/g/3nk0+6tfa8IMZlXe6x4dzrYVzgjlD8uGRUAxZZdP7vf
UeHWHxW1rmCFZANq98Y7nIaBsPhZd1XsVZOEbw/KsQKBgQDbzbmBALc9rpQDPgeZ
U6mfqfueLQKW8Kz/eO1BFNIa6bomXfo+/iVEomEdv9pqJs3CqKsOMFxgK53kQMa6
1AvQqPmg3z3+m17MzSHPwcWtYP22xQde/m3qPTdG+mPfZ80ASpybejRjOi/NKCPg
bpXTE7HTeGZsikH8LFURuE1HswKBgQDDfPjDGNgf63GNGsrPaT4vGMGT5WnmCVbO
LVvNpnkP/wJdrpsQb2dBX09yEvFACJkPQz2Vqm49LIMN+4uOzy8pw1qPIJpjGdzN
5Zko/cpV3wkGi0Id6xtnengMMdJwTbg5T8iMXcO9bsXseg1Zva3xnb5hDF+Aubkt
DERywcG15QKBgQDVzo6kipK0AE5fvQXdQoFcGxfzq+q58lEFjJaUWPFrVnFJgt66
SbLsyVrYele2LBq4QCNsAOTKc4L5lXz6HOuFQ+jWcHE4ad/ULbG3CtEDrrX9BDkA
UVOPp45Oj594n9rMbsdZgYzV/LKkyGfllwxMLvsqLhLLf81hw6nYO8OIewKBgGaW
NpVrfD+D9trtrHCb8h4VB8DtK12kmQEpnHuXWQCj+kHfV1CQpccQlUhv2FqaKHhx
+OeJwMApk7zKvLn8z+tCsUta+Kn48H68dlukk4HswXfFrLS2pHLxOf5sRtrYbkzl
KYE/03CdqRAoHMlzWMzq0vVq4NNUo3CYd3Mhat5hAoGACXyUftfbuQIuxjJgpmwV
8GwTOv2B3bofWvchn4CfE3NG3+fM8FJaY7CalLer2BQ8024q2YOj0D6R4n/qhCpn
bQ+y7n4ODuumATiOy029UoAvrUTjzlU0KXbZUZXShxgW/D/ghEtNPmQRwalxl2ch
HaJsSQmVWpVuPGgB4J6jpWU=
-----END PRIVATE KEY-----
"""
client_email = "1027868760189-compute@developer.gserviceaccount.com"
client_id = "109731033304983614561"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/1027868760189-compute%40developer.gserviceaccount.com"
universe_domain = "googleapis.com"
